[id="add-custom-cert"]
= Adding custom certificates
include::ROOT:partial$common-attributes.adoc[]
:context: add-custom-cert

:source-highlighter: highlight.js

[role="_abstract"]
Learn how to use a custom TLS certificate with {product-title}. After you set up a certificate, users and API clients do not have to bypass the certificate security warnings when connecting to Central.


[id="add-custom-security-cert"]
== Adding a custom security certificate
You can apply a security certificate during the installation or on an existing {product-title} deployment.

//Prerequisites
include::ROOT:partial$custom-cert-prerequisites.adoc[leveloffset=+2]

//During a new installation
include::ROOT:partial$custom-cert-new-install.adoc[leveloffset=+2]

//On an existing installation
include::ROOT:partial$custom-cert-existing.adoc[leveloffset=+2]

[id="configure-sensor-to-trust-cert"]
== Configuring Sensor to trust custom certificates
If you are using a custom certificate that is not trusted globally, you must configure the Sensor to trust your custom certificate.
Otherwise, you might get errors.
The specific type of error may vary based on your setup and the certificate you use.
Usually, it is an `x509 validation` related error.

[NOTE]
====
You do not need to configure the Sensor to trust your custom certificate if you are using a globally trusted certificate.
====
//Downloading the Sensor bundle
include::ROOT:partial$download-sensor-bundle.adoc[leveloffset=+2]

//When deploying a new Sensor
include::ROOT:partial$trust-cert-new-sensor.adoc[leveloffset=+2]

//On an existing Sensor
include::ROOT:partial$trust-cert-existing-sensor.adoc[leveloffset=+2]

If you added the certificates to an existing sensor, you must restart the Sensor container.

//Restart Sensor
include::ROOT:partial$restart-sensor-container.adoc[leveloffset=+3]
