[id="respond-to-violations"]
= Responding to violations
include::ROOT:partial$common-attributes.adoc[]
:context: respond-to-violations

:source-highlighter: highlight.js

[role="_abstract"]
Using {product-title} you can view policy violations, drill down to the actual cause of the violation, and take corrective actions.

{product-title} built-in policies identify a variety of security findings, including vulnerabilities (CVEs), violations of DevOps best practices, high-risk build and deployment practices, and suspicious runtime behaviors.
Whether you use the default out-of-box security policies or use your own custom policies, {product-title} reports a violation when an enabled policy fails.

include::ROOT:partial$violations-view.adoc[leveloffset=+1]

[id="view-violation-details"]
== Viewing violation details
When you select a violation in the *Violations* view, the *Violation Details* panel opens on the right.

The *Violation Details* panel shows detailed information grouped by multiple tabs.

include::ROOT:partial$violation-view-violation-tab.adoc[leveloffset=+2]

[id="using-comments-and-tags"]
==== Using comments and tags
You can use tags and comments to specify what is happening with violations to keep your team up to date.
Comments allow you to add text notes to violations and tags allow you to categorize your violations.

:smallporv: violation
:smallpluralporv: violations
:capsporv: Violation
:capspluralporv: Violations

include::ROOT:partial$adding-comments.adoc[leveloffset=+4]

include::ROOT:partial$adding-tags.adoc[leveloffset=+4]

include::ROOT:partial$violation-view-enforcement-tab.adoc[leveloffset=+2]

include::ROOT:partial$violations-view-deployment-tab.adoc[leveloffset=+2]

include::ROOT:partial$violation-view-policy-tab.adoc[leveloffset=+2]
