[id="review-cluster-configuration"]
= Reviewing cluster configuration
include::ROOT:partial$common-attributes.adoc[]
:context: review-cluster-configuration



[role="_abstract"]
Learn how to use the *Configuration Management* view and understand the correlation between various entities in your cluster to manage your cluster configuration efficiently.

Every {ocp} cluster includes many different entities distributed throughout the cluster, which makes it more challenging to understand and act on the available information.

{product-title} (RHACS) provides efficient configuration management that combines all these distributed entities on a single page.
It brings together information about all your clusters, namespaces, nodes, deployments, images, secrets, users, groups, service accounts, and roles in a single *Configuration Management* view, helping you visualize different entities and the connections between them.

include::ROOT:partial$using-the-configuration-management-view.adoc[leveloffset=+1]

[id="misconfigurations-kubernetes-rbac"]
== Identifying misconfigurations in Kubernetes roles

You can use the *Configuration Management* view to identify potential misconfigurations, such as users, groups, or service accounts granted the `cluster-admin` role, or roles that are not granted to anyone.

include::ROOT:partial$kubernetes-role-assignment.adoc[leveloffset=+2]

include::ROOT:partial$service-accounts-permissions.adoc[leveloffset=+2]

include::ROOT:partial$unused-kubernetes-roles.adoc[leveloffset=+2]

include::ROOT:partial$view-kubernetes-secrets.adoc[leveloffset=+1]

include::ROOT:partial$find-policy-violations.adoc[leveloffset=+1]


[id="comments-and-tags-on-policy-violations"]
=== Commenting and tagging on policy violations

You can use comments and tags to specify what is happening with violations to keep your team up to date.
Comments allow you to add text notes to violations and tags allow you to categorize your violations.

:smallporv: violation
:smallpluralporv: violations
:capsporv: Violation
:capspluralporv: Violations

include::ROOT:partial$adding-comments.adoc[leveloffset=+3]

include::ROOT:partial$adding-tags.adoc[leveloffset=+3]

include::ROOT:partial$find-failing-cis-controls.adoc[leveloffset=+1]
